name = "starmap"
version = "0.1.0"

description = "Type-Safe, ORM-like SQL Library for gleam"
licences = ["MIT"]
repository = { type = "github", user = "MoeDevelops", repo = "starmap" }
links = []

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
sqlight = ">= 0.9.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
